name: 'Build and Deploy to GKE'

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy-jobs:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v4'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{key}}
      - name: Deploy to Cloud Run
        run: |-
         gcloud run jobs deploy docker-python \
          --project=canvas-abacus-416507 \
          --region=us-central1 \
          --no-allow-unauthenticated \
          --service-account=988242885954-compute@developer.gserviceaccount.com
